export const componentMaptoName={
    CaptureReportTemplate: "Capture Report Template",
    RegOpzDataGrid: "Data Grid",
    MaintainBusinessRules: "Maintain Business Rules",
    AddBusinessRule: "Add Business Rule",
    ViewDataComponentV2: "View Data",
    ViewDataComponent: "View Data Grid",
    ViewReport: "View Report",
    CreateReport: "Create Report",
    DrillDown: "DrillDown",
    MaintainReportRules: "Maintain Report Rules",
    AddReportRules: "Add Report Rules",
    AddReportAggRules: "Add Report Aggregate Rules",
    MaintainSources: "Maintain Sources",
    AddSources: "Add Sources",
    VarianceAnalysisForm: "Variance Analysis",
    VarianceAnalysisGrid: "Variance Analysis Grid",
    VarianceAnalysisChart: "Variance Analysis Chart",
    ManageDefChange: "Manage Definition Change",
    ManageRoles: "Role Management",
    AddRoles: "Add Role",
    ManageUsers: "User Management"
}
